### ISSUE TITLE
Assess Harmony integration

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#183]

**Comment by guidiaz** [comment]
‌Harmony is a fast and secure blockchain for decentralized applications. The production mainnet supports 4 shards of 1000 nodes, producing blocks in 2 seconds with finality.

The Effective Proof-of-Stake (EPoS) reduces centralization while supporting stake delegation, reward compounding and double-sign slashing.

Harmony aims to build an open network of nodes operated and governed by a large community. This node community is called Pangaea.

**Comment by guidiaz** [comment]
**Key Innovations**:
- ***Fully scalable architecture**: Harmony’s sharding works not only on the network communication and transaction validation, but also on the blockchain state. This makes Harmony fully scalable on all three aspects of the blockchain: network, storage and transaction processing.*

**Comment by guidiaz** [comment]
Harmony ONE is an Ethereum EVM 100% compatible blockchain, and is very good at decentralized application (Dapp) development within many possible verticals including DeFi, NFT, Gaming, and many others:
- https://www.youtube.com/watch?v=rFmVIA6Jvmg

**Comment by guidiaz** [comment]
However:
- Harmony nodes provide means at the JSONRPC level to let apps sign for Harmony special kind of transactions: staking transactions, cross-shard transactions, ... Should we need to handle these for any reason, we would be needing to create a special web3-jsonrpc gateway for Harmony. In this case, there's a [Harmony Ethers.js Wrapper](https://github.com/harmony-one/harmony-ethers-sdk) available.
- There's also a CALL2 Harmony-specific opcode available for smart contracts needing to call contracts deployed in different shards.

**Comment by guidiaz** [comment]
Concerning Randomness in Harmony:
- Harmony brings the technology of VRF (Verifiable Random Function) natively on chain to create a optimal solution for randomness that is unpredictable, unbiasable, verifiable and immediately available. 
- The VRF data are available to be consumed by any chain clients by querying the block header. 
- ***VRF data are also available in the smart contract level via a new EVM precompiled contract at address `0xff`***. Any smart contract on Harmony can access it with following solidity assembly code:
  ```solidity
  function vrf() public view returns (bytes32 result) {
    uint[1] memory bn;
    bn[0] = block.number;
    assembly {
      let memPtr := mload(0x40)
      if iszero(staticcall(not(0), 0xff, bn, 0x20, memPtr, 0x20)) {
        invalid()
      }
      result := mload(memPtr)
    }
  }
  ```

**Comment by guidiaz** [comment]
Other particularities:
- HDWallets in Harmony follow a different derivationPath: `m/44'/1023'/0'/0`
- Harmony uses bech32 address format with `one1` prefix. However, Ethereum style hex address can also be used.

**Comment by guidiaz** [comment]
Will try to deploy contracts to Harmony Testnet:
- [ ] Use faucet to get 1000 ONE 
- [ ] Set-up Ethers gateway against https://api.s0.b.hmny.io (shard #0)
- [ ] Witnet Solidity Bridge:
  - WitnetDecoderLib: 
  - WitnetParserLib:
  - WitnetPriceRouter:
  - WitnetProxy:
  - WitnetRequestBoardTrustableDefault:
- [ ] Witnet Pricefeeds:
  - Price-BTC/USD-6:
  - Price-ETH/USD-6:
