### ISSUE TITLE
Assess Moonbeam integration

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#186]
https://docs.moonbeam.network/

**Comment by guidiaz** [comment]
One of the design goals of Moonbeam is to create an environment that is as close as possible to Ethereum, and to offer a set of Web3 RPC endpoints that are compatible with Ethereum. However, Moonbeam is also a Substrate based chain, which means that it exposes Substrate RPCs, and that it has integral functionality that is powered by Substrate such as Staking, Governance, and other features which are not part of the Ethereum API.

**Comment by guidiaz** [comment]
Ethereum JSON RPC methods currently supported by Moonbeam: 
- https://docs.moonbeam.network/builders/get-started/eth-compare/rpc-support/

**Comment by guidiaz** [comment]
**Using MetaMask**:
- **Moonriver** (testnet):
  - Chain id: 1285
  - Symbol: MOVR
  - Provider URL: https://rpc.api.moonriver.moonbeam.network
  - Explorer URL: https://moonriver.moonscan.io/
- **Moonbeam** (mainnet):
  - Chain id: 1284
  - Symbol: GLMR
  - Provider URL: https://rpc.api.moonbeam.network
  - Explorer URL: https://blockscout.moonbeam.network/

**Comment by guidiaz** [comment]
**Moonbase Alpha faucet**:
- Connect to [Discord channel ](https://discord.gg/PfpUATX)
- Under "Miscellaneous" category, #Moonbase-Faucet channel, type: `!faucet send <evm_address>`
- Additional 5 DEV tokens can be claimed every 24 hours

**Comment by aesedepece** [comment]
AFAIK, Moonriver is much more popular than Moonbase Alpha. But at the same time, it's not an apples to apples comparison. As Moonriver runs on Kusama and has its own utility token ([MOVR](https://coinmarketcap.com/currencies/moonriver/)), it is more like a stepping stone into the Moonriver ecosystem than a testnet in the "hey this is a test chain to deploy contracts for free" sense.

**Comment by guidiaz** [comment]
Exactly :-) For now, we'll try to deploy on Moonbase Alpha just for free, considering also the official description for Moonbase Alpha: "This testnet is a network hosted by PureStake. It features a parachain/relay chain scheme. The goal is to allow developers to test the Ethereum compatibility features of Moonbeam in a shared parachain environment without needing to run their own nodes or network."

**Comment by guidiaz** [comment]
Witnet Solidity Bridge deployed on Moonbase Alpha:
  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d`](https://moonbase.moonscan.io/address/0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d)
    * WitnetParserLib: [`0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0`](https://moonbase.moonscan.io/address/0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0)
    * WitnetProxy: [**`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`**](https://moonbase.moonscan.io/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)
    * WitnetRequestBoardTrustableDefault: [`0x225BAd150B9D5202DC805B34A0DF64B1a77459dF`](https://moonbase.moonscan.io/address/0x225BAd150B9D5202DC805B34A0DF64B1a77459dF)
  
  - **Witnet use cases**:
    - WitnetPriceRouter: [**`0x56834Ff8D4b27db647Da97CA3bd8540f7fA0e89D`**](https://moonbase.moonscan.io/address/0x56834Ff8D4b27db647Da97CA3bd8540f7fA0e89D)

**Comment by guidiaz** [comment]
Created 'bridgemoonbase' stack on bootstrap machine.

**Comment by guidiaz** [comment]
> Ethereum JSON RPC methods currently supported by Moonbeam:
> 
> * https://docs.moonbeam.network/builders/get-started/eth-compare/rpc-support/

`eth_getFilterChanges` seems not to be implemented, nor by the general public (metamask) rpc provider, nor a moonbase alpha endpoint created on Bware Labs platform (infura alik). While this doesn't prevent the whole request/complete workflow to complete, it could eventually turn into an inconvenience if either the poller and/or bridge node start to lack responsiveness because of this. New configuration parameter will be added to the web3-jsonrpc-gateway/ethers implementation as an optional way to mock responses to `eth_getFilterChanges` requests.

**Comment by guidiaz** [comment]
Same thing happening w/ endpoints created on Bware Labs:
- New ETHERS_MOCK_FILTERS will be added to web3-jsonrpc-gateway/ethers implementation.
