### ISSUE TITLE
Assess variants to `UsingWitnet._witnetPostRequest(..)`

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#193]
As current implementation will take the whole `msg.value` when internally calling to the WRB.

**Comment by guidiaz** [comment]
I can think of two non-excluding variants:

- Estimate required reward before posting the request:
    ```solidity
    function _witnetPostRequest(IWitnetRequest _request)
        internal
        returns (uint256)
    {
        uint256 _reward = witnet.estimateReward(tx.gasprice);
        return witnet.postRequest{value: _reward}(_request);
    }
    ```
- Let caller specify reward by parameter:
    ```solidity
    function _witnetPostRequest(IWitnetRequest _request, uint256 _reward)
        internal
        returns (uint256)
    {
        return witnet.postRequest{value: _reward}(_request);
    }
    ```

A possible drawback of the first option is that it would not be Boba compatible, as GASPRICE opcode is forbidden.

**Comment by aesedepece** [comment]
I tend to think that option B is better because it's cheaper. Calculating `_reward` onchain offers no actual advantage because the value of the `_witnetPostRequest` transaction needs to be calculated offchain by the EOA by web3-calling `estimateReward`  upfront anyway.

**Comment by clbartoli** [comment]
I like the second option too! It used to work like that when we had rewards for posting the request and reporting the result from witnet

**Comment by mariocao** [comment]
Fine for me too! :+1:

**Comment by guidiaz** [comment]
Excellent, B will be ;-)

**Comment by mariocao** [comment]
The changes in the `price_feed_poller` shouldn't be too much as AFAIK it already estimates the reward to set the transaction `value`. :)

**Comment by aesedepece** [comment]
At a second thought, I'm perfectly fine with option A, and actually prefer it over B.

I hadn't realized that the code snippets that @guidiaz shared were actually not part of a client contract's code but rather in the wrapping that `UsingWitnet` does around the raw `witnet.postRequest` function.

As the purpose of `UsingWitnet` is to increase the degree of convenience and abstraction for the user, it feels reasonable to deal with the `estimateReward` thing at that point, so the API remains the same as we have today.

At the end of the day, there's no point in using a reward that is higher than what `estimateReward` will tell us.

**Comment by guidiaz** [comment]
In order to allow Boba-compatible implementation of new `_postWitnetRequest(IWitnetRequest)`, it shall be declared as `virtual`.

**Comment by guidiaz** [comment]
`_witnetUpgradeReward` should be re-implemented in the same way as `_witnetPostRequest`. Because of this, better to make these two methods rely on a EVM-agnostic version of `_witnetEstimateReward(uint256)`, i.e. `_witnetEstimateReward()`:

```solidity
  function _witnetEstimateReward()
    internal view
    virtual
  {
    return witnet.estimateReward(tx.gasprice);
  }

  function _witnetUpgradeRequest(uint256 _id)
    internal
    virtual
  {
    witnet.upgradeReward{value: _witnetEstimateReward()}(_id);
  }

  function _witnetPostRequest(IWitnetRequest _request)
    internal
    virtual
    returns (uint256)
  {
    return witnet.postRequest{value: _witnetEstimateReward()}(_request);
  }
```

**Comment by guidiaz** [comment]
Then again, the former approach (to accomplish with **A**), the `_witnetEstimateReward()` should actually be left unimplemented. So A approach would rather be:

```solidity
  function _witnetEstimateReward() internal view virtual;

  function _witnetUpgradeRequest(uint256 _id)
    internal
    virtual
  {
    witnet.upgradeReward{value: _witnetEstimateReward()}(_id);
  }

  function _witnetPostRequest(IWitnetRequest _request)
    internal
    virtual
    returns (uint256)
  {
    return witnet.postRequest{value: _witnetEstimateReward()}(_request);
  }
```

Otherwise, it will break compilation of "UsingWitnet" when trying to migrate artifacts to Boba-based networks. The same would happen if `tx.gasprice` was used in either `_witnetUpgradeRequest` or `_witnetPostRequest`. In other words, **A** implies that any contract inheriting from UsingWitnet will have to provide an implementation for `_witnetEstimateReward()`.

**Comment by guidiaz** [comment]
In the other hand, the full **B** approach could be something like this:

```solidity
  function _witnetUpgradeRequest(uint256 _id, uint256 _gasPrice)
    internal
    virtual
  {
    witnet.upgradeReward{value: _witnetEstimateReward(_gasPrice)}(_id);
  }

  function _witnetPostRequest(IWitnetRequest _request)
    internal
    virtual
    returns (uint256)
  {
    return witnet.postRequest{value _witnetEstimateReward(_gasPrice)}(_request);
  }
```

**Comment by guidiaz** [comment]
Prototype implementation:
- https://github.com/witnet/witnet-ethereum-bridge/pull/194
