### ISSUE TITLE
Update name of the repository in README and package.json, and deprecate the old one

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#199]
This repository is now named `witnet-solidity-bridge`.

We now need to update the README title, as well as the package name on `package.json`.

Then we need to deprecate the old `witnet-ethereum-bridge` NPM package with `npm deprecate`, which allows for a chosing custom message that can instruct the users to replace the old package for the new one.

After that, we will also need to update the name of the packages inside all our ecosystem's repos.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/witnet-solidity-bridge/199?planning-poker) with ZenHub @aesedepece @aeweda @gabaldon @guidiaz

**Comment by Tommytrg** [comment]
Everything is already done
