### ISSUE TITLE
Assess REEF integration

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#221]
Quick Start
https://docs.reef.io/docs/developers/quick-start/

Resources
https://docs.reef.io/docs/developers/resources/

Nodes
https://docs.reef.io/docs/developers/nodes/

Networks
https://docs.reef.io/docs/developers/networks/

Accounts
https://docs.reef.io/docs/developers/accounts/

Reef Console
https://console.reefscan.com/

Reef Remix IDE
https://remix.reefscan.com/

Reef Hardhat Plugin
https://github.com/reef-defi/hardhat-reef

Reef Python Interface
https://github.com/reef-defi/py-reef-interface

Reef Chain Onboarding Form
https://airtable.com/shrWG6k37KyWQIGSX

Reef Developer Grants Program
https://medium.com/reef-finance/reef-finance-launches-20m-grant-fund-to-expand-reef-chain-development-bca4cb9f53a9

Reef Developer Grants Application Form
https://airtable.com/shrOJ7q8xZcSS5h3W

**Comment by guidiaz** [comment]
- Reef Chain is an EVM compatible chain for DeFi, with Nominal Proof of Stake as consensus mechanism.
- Reef has predictable algorithmic fee model. All fees from Reef Chain are automatically burned.
- Reef Chain is known to be "on-chain upgradable" (sic)
- Block time is ~10 seconds, tx finality ~40 seconds, and declares a throughput of 465 tps

**Comment by guidiaz** [comment]
**Reef mainnet**:
- The Reef mainnet went live on May 28th, 2021
- Chain id: 13939
- HTTP RPC: https://rpc.reefscan.com

**Comment by guidiaz** [comment]
**Reef testnet**:
- Reef testnet tokens have no value and may be destryed on testnet upgrades. 
- Chain id: 13939 (same as mainnet??)
- HTTP RPC: https://rpc-testnet.reefscan.com

**Comment by guidiaz** [comment]
**Accounts**:
- New accounts:
  - SS58 Addresses
  - To create a Reef chain account, we need to deposit at least 1 REEF into it. This is known as "existential deposit".
- EVM accounts:
  - Once we have a Reef Chain account, we need to oink an EVM account to it. This can be done by either generating a default EVM address or importing an existing Ethereum address. **Each Reef account can be inked to exactly one EVM account.**
  - Reef chain accounts are based on SR25519 and their pulibc keys (addresses) are encoded with SS58 (e.g. `5H1tqyqYgBhYky3rMwjwmR9uNrBMrm45EaF8c9UQoxuVAmRA`)
  - Ethereum accounts are based on ECDSA and their public keys (addresses) are hex encoded (e.g. `0xebdcfce3377bd7593f14a4c70ed2974d55a1ab96`)

**Comment by guidiaz** [comment]
**Generating a default EVM address**:
- All we have to do is use EVM, and an address will be auto-generated and assigned to our account on the first EVM call.
- Alternatively, we can generate the default address manually by calling the `evmAccounts.claimDefaultAccount()` function. This will create an EVM address for our Reef chain account.
- To see our EVM address we can call evmAccounts.evmAddresses(AccountId)

**Comment by guidiaz** [comment]
**Linking an existing Ethereum address**:
- To import an existing Ethereum address into Reef chain, and assign it to a Reef Account, we can call the `evmAccounts.claimAccount(eth_address, eth_signature)` function. A valid signature is needed to verify the ownership of the address.

**Comment by aesedepece** [comment]
Interesting. Thanks for the info. Can all of these particularities be abstracted away by the gateway?

**Comment by guidiaz** [comment]
A specific JSON RPC gateway will be required for Reef integration. While a [Javascript SDK/library](https://github.com/reef-defi/evm-provider.js) is provided for interacting w/ Reef nodes, it is not fully implemented at the moment. For instance, methods like `sendTransaction` or `sendRawTransaction` methods are not supported. Moreover, while it should be possible to interact w/ the node at a lower level via the underlying polkadot api, it seems it's either not well initialized, or Reef nodes are just not prepared to reply to methods like `eth_getTransactionReceipt`.

**Comment by guidiaz** [comment]
Unfortunately, integration will be blocked until a more advanced `@reef/evm-provider` library is provided.

**Comment by Tommytrg** [comment]
To unlock this integration, the Reef team suggest to use `sendTransaction` from https://github.com/reef-defi/evm-provider.js/blob/master/src/Signer.ts. It can be used in the following way: 


```js
const Tx = require("ethereumjs-tx");
const ethers = require("ethers");

const sendEths = async ({
  to,
  from,
  fromPrivateKey,
  value,
  gasPrice,
  gasLimit = ethers.utils.hexlify(21000),
}) => {
  const txCount = await provider.getTransactionCount(from);
  // build the transaction
  const tx = new Tx({
    nonce: ethers.utils.hexlify(txCount),
    to,
    value: ethers.utils.parseEther(value).toHexString(),
    gasLimit,
    gasPrice,
  });
  // sign the transaction
  tx.sign(Buffer.from(fromPrivateKey, "hex"));
  // send the transaction
  const { hash } = await provider.sendTransaction(
    "0x" + tx.serialize().toString("hex")
  );
  await provider.waitForTransaction(hash);
};
```

Code retrieved from here: https://ethereum.stackexchange.com/questions/80867/sample-code-in-ethers-js-to-send-raw-transaction-and-to-sign-transaction/94546#94546

**Comment by aesedepece** [comment]
Shall we retry this on the next sprint?

**Comment by guidiaz** [comment]
We'll check if the integration can be unblocked.

**Comment by guidiaz** [comment]
Solved on https://github.com/witnet/internal/issues/196

**Comment by aesedepece** [comment]
What an absolute satisfaction to close this one!
