### ISSUE TITLE
Assess Cronos Chain integration

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#226]
- https://cronos.org
- https://cronos.org/docs/chain-details/introduction.html
- https://cronos.org/docs/getting-started/

**Comment by guidiaz** [comment]
- Crypto.org introduces the Cronos mainnet beta, the Cosmos SDK based EVM compatible chain, on 8 Nov 2021.
- Cronos is the EVM compatible chain running in parallel to the Crypto.org Chain. It aims to massively scale the Chain DeFi ecosystem, by providing developers with the abiity to rapidly port apps from Ethereum and EVM-compatible chains, and access the 10M+ user base of the Crypto.com ecosystem.
- Cronos is powered by **[Ethermint](https://github.com/tharsis/ethermint)**. Ethermint is a scalable and interoperable Ethereum library, built on Proof-of-Stake with fast-finality using the **Cosmos SDK** which runs on top of [**Tendermint Core**](https://github.com/tharsis/ethermint) consensus engine. Tendermint Core is a Byzantine Fault Tolerant (BFT) middleware that takes a state transition machine (written in any programming language), and securely replicates it on many machines

**Comment by Tommytrg** [comment]
### Block explorer
**Mainnet**
https://cronoscan.com/

**Testnet**
https://cronos.org/explorer/testnet3

### Faucet
https://cronos.org/faucet

**Comment by Tommytrg** [comment]
**Networks**
https://cronos.org/docs/chain-details/chain-id.html#chain-id

**Faucet**
https://cronos.org/faucet

**Comment by Tommytrg** [comment]
**Grants**
https://cronos.org/grants

**Comment by guidiaz** [comment]
- **Mainnet**: 
  - RPC endpoint: https://evm.cronos.org
  - Chain id: 25
  - Symbol: CRO
  - Explorer: https://cronos.org/explorer
- **Testnet**:
  - RPC endopoint: https://evm-t3.cronos.org
  - ...

**Comment by guidiaz** [comment]
**CRONOS.TESTNET**:

- Master account: [**`0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B`**](https://cronos.org/explorer/testnet3/address/0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B)

- **Witnet Solidity Bridge**:
  * WitnetDecoderLib: [`0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb`](https://cronos.org/explorer/testnet3/address/0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb)
  * WitnetParserLib:  [`0x7D8A488BACB56dA2De17628e26a21fFd97792b81`](https://cronos.org/explorer/testnet3/address/0x7D8A488BACB56dA2De17628e26a21fFd97792b81)
  * WitnetProxy:  [**`0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431`**](https://cronos.org/explorer/testnet3/address/0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431)
  * WitnetRequestBoardTrustableDefault:
    * v0.5.5: [`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`](https://cronos.org/explorer/testnet3/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)

**Comment by guidiaz** [comment]
Min. gas price on testnet ~ 2000 GWEI , so deploying the WRB required ~ 18 tCRO

**Comment by guidiaz** [comment]
**CRONOS.TESTNET**
- **Witnet use cases**:
  * WitnetPriceRouter: [**`0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0`**](https://cronos.org/explorer/testnet3/address/0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0)
    * WitnetRandomness: [**`0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f`**](https://cronos.org/explorer/testnet3/address/0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f)
- **Witnet price feeds**:
    * Price-BTC/USD-6: [`0x9E943Ab1FD0D35B3BaDe31AA78D60C485EA1a604`](https://cronos.org/explorer/testnet3/address/0x9E943Ab1FD0D35B3BaDe31AA78D60C485EA1a604)
    * Price-CRO/USDT-6: [`0x70639D6D08a18aa200de08E08970B53036B0B3d9`](https://cronos.org/explorer/testnet3/address/0x70639D6D08a18aa200de08E08970B53036B0B3d9)
    * Price-ETH/USD-6: [`0x4092CC222B1bD1176D8a8cBE4070ccea66E9d1D6`](https://cronos.org/explorer/testnet3/address/0x4092CC222B1bD1176D8a8cBE4070ccea66E9d1D6)
    * Price-USDT/USD-6: [`0xdD35D2F17B510348fA37D91CB51f8FB0388f2f55`](https://cronos.org/explorer/testnet3/address/0xdD35D2F17B510348fA37D91CB51f8FB0388f2f55)

**Comment by guidiaz** [comment]
Testnet addresses updated on docs site: 
- https://docs.witnet.io/smart-contracts/supported-chains
- https://docs.witnet.io/smart-contracts/witnet-data-feeds/addresses/cronos
- https://docs.witnet.io/smart-contracts/witnet-randomness-oracle/contract-addresses#cronos-chain
- https://docs.witnet.io/smart-contracts/apis-and-http-get-post-oracle/contracts-addresses#cronos-chain

**Comment by aesedepece** [comment]
Assessment and implementation are now complete.
