### ISSUE TITLE
Assess OKC integration

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#234]
OKC is the OKX chain.

Integration docs:
https://okc-docs.readthedocs.io/en/latest/developers/quick-start.html

**Comment by guidiaz** [comment]
Got some OKT from https://discord.gg/B5nMs6qK5F

**Comment by guidiaz** [comment]
WitnetRequestBoardTrustableDefault could not get verified. The explorer says: "Try again later"

**Comment by guidiaz** [comment]
Prototyped new pricefeed Price-OKT/USDT-6:
- https://github.com/witnet/witnet-price-feed-examples/pull/92

**Comment by guidiaz** [comment]
**OKX Chain Testnet**:
  - **Witnet price feeds**:
    * Price-OKT/USDT-6: [`0xD9465D38f50f364b3263Cb219e58d4dB2D584530`](https://www.oklink.com/en/okc-test/address/0xD9465D38f50f364b3263Cb219e58d4dB2D584530)
    * Price-USDT/USD-6: [`0x56834Ff8D4b27db647Da97CA3bd8540

**Comment by guidiaz** [comment]
Witnet Price Poller v1.1.0 and Witnet Bridge v1.5.0 up and running on OKX Chain testnet.

**Comment by guidiaz** [comment]
First Witnet txs from OKXChain Testnet:
- Price-OKT/USDT-6 update history: https://witnet.network/search/7cad84113642e98eaf1d673935ed2adeadf9df152686bdfafc16d52a7e0df4a5
- First randomness request: https://witnet.network/search/b23a2a80181f9e24a49c65a52a214b80e2bbb79c62998f26e345f428396d90a3

**Comment by guidiaz** [comment]
**OKX Chain Mainnet**:

  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x400DbF3645b345823124aaB22D04013A46D9ceD5`](https://polygonscan.com/address/0x400DbF3645b345823124aaB22D04013A46D9ceD5#code)
    * WitnetParserLib: [`0x1D9c4a8f8B7b5F9B8e2641D81927f8F8Cc7fF079`](https://polygonscan.com/address/0x1D9c4a8f8B7b5F9B8e2641D81927f8F8Cc7fF079#code)
    * WitnetProxy: [**`0xd653fbd7c736838289262F0F41A458f35393C88a`**](https://polygonscan.com/address/0xd653fbd7c736838289262F0F41A458f35393C88a#code)
    * WitnetRequestBoardTrustableDefault: [`0x916aC9636F4Ea9f54f07c9De8fDCd828e1b32c9B`](https://polygonscan.com/address/0x916aC9636F4Ea9f54f07c9De8fDCd828e1b32c9B#code)

  - **Witnet use cases**:
    * WitnetPriceRouter: [**`0x3806311c7138ddF2bAF2C2093ff3633E5A73AbD4`**](https://polygonscan.com/address/0x3806311c7138ddF2bAF2C2093ff3633E5A73AbD4#code)
    * WitnetRandomness: [**`0xE22f48DDdcb34BD34489fE224d7fFC1b0a361D87`**](https://polygonscan.com/address/0xE22f48DDdcb34BD34489fE224d7fFC1b0a361D87#code)     
  - **Witnet Pricefeeds**:
    * Price-BTC/USD-6: [`0xF262d3F1d403042dFB7998Bff860b924B84A2Df6`](https://polygonscan.com/address/0xF262d3F1d403042dFB7998Bff860b924B84A2Df6#code)
    * Price-DAI/USD-6: [`0x6490791Af2Bf2f2eaC7D6A3d3F6E2FD57399623a`](https://polygonscan.com/address/0x6490791Af2Bf2f2eaC7D6A3d3F6E2FD57399623a#code)
    * Price-ETH/USD-6: [`0xBaaF31F4AAc5ab5334b6E239a83bf4E855C55ea7`](https://polygonscan.com/address/0xBaaF31F4AAc5ab5334b6E239a83bf4E855C55ea7#code)
    * Price-VSQ/DAI-6: [`0x93A11f01D14c0f08d5DDa632DD84821482d148E5`](https://polygonscan.com/address/0x93A11f01D14c0f08d5DDa632DD84821482d148E5#code)

**Comment by guidiaz** [comment]
Witnet Price Poller v1.1.0 and Witnet Bridge v1.4.3 up and running on **OKX Chain mainnet**.

**Comment by guidiaz** [comment]
Witnet txs:
- First price update: https://witnet.network/search/a6f1f12ff11d185e9377cae95e7e721de8fce386d72e6561c8becabd67051e11
- First randomness: https://witnet.network/search/69abe761c1955d9a1438fcaafbd53a8bfc65d6833cea7bfe5d5fb374549e07f9

**Comment by guidiaz** [comment]
Published Witnet Solidy Bridge contracts, and first two price feeds:
- https://docs.witnet.io/smart-contracts/supported-chains
- https://docs.witnet.io/smart-contracts/witnet-data-feeds/price-feeds-registry
- https://docs.witnet.io/smart-contracts/witnet-randomness-oracle/contract-addresses#okx-chain
- https://docs.witnet.io/smart-contracts/apis-and-http-get-post-oracle/contracts-addresses#okx-chain

**Comment by aesedepece** [comment]
This is complete now!
