### ISSUE TITLE
Assess KAVA integration

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#241]
https://docs.kava.io/docs/intro/

**Comment by guidiaz** [comment]
Testnet:
- Network Name: Kava EVM Alphanet
- New RPC URL: https://evm.evm-alpha.kava.io/
- Chain ID: 2221
- Currency Symbol: tKAVA
 Explorer URL: https://explorer.evm-alpha.kava.io/

**Comment by guidiaz** [comment]
Kave Testnet faucet website found at https://faucet.kava.io/.

**Comment by guidiaz** [comment]
On **Kava Testnet**:
- use address # 0 for poller: [`0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B`](https://explorer.evm-alpha.kava.io/address/0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B/transactions)
- use address # 2 for bridge: [`0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77`](https://explorer.evm-alpha.kava.io/address/0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77/transactions)

**Comment by guidiaz** [comment]
Created pull request on docs for adding Kava Testnet addresses.
