### ISSUE TITLE
Assess chain integration with Cube Chain

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#254]
https://docs.cube.network/#/

**Comment by guidiaz** [comment]
Got 0.5 CUBET from the faucet:
- https://testnet.cubescan.network/en-us/tx/0x4ee04f67ab83fd65902e3b0028c5ef0dc892df8fe626cec75d114ea8fef759e0

**Comment by aesedepece** [comment]
> Got 0.5 CUBET from the faucet:
> 
>     * https://testnet.cubescan.network/en-us/tx/0x4ee04f67ab83fd65902e3b0028c5ef0dc892df8fe626cec75d114ea8fef759e0

I just got you some more to get started :stuck_out_tongue_winking_eye: 

- https://testnet.cubescan.network/en-us/tx/0x5c2356024a0e40a6a0d9d6d5aa049237d24271d3a32a59864701b30b799e7923

**Comment by guidiaz** [comment]
Apparently, on testnet cubesan:
- Libraries/contracts linked to external libs cannot get verified
- Delegatable proxies cannot get verified

**Comment by guidiaz** [comment]
Cube Chain Testnet:
  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb`](https://testnet.cubescan.network/address/0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb)
    * WitnetParserLib:  [`0x7D8A488BACB56dA2De17628e26a21fFd97792b81`](https://testnet.cubescan.network/address/0x7D8A488BACB56dA2De17628e26a21fFd97792b81)
    * WitnetProxy:  [**`0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431`**](https://testnet.cubescan.network/address/0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431)
    * WitnetRequestBoardTrustableDefault: [`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`](https://testnet.cubescan.network/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)

  - **Witnet use cases**:
    * WitnetPriceRouter: [**`0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f`**](https://testnet.cubescan.network/address/0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f)
    * WitnetRandomness: [**`0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0`**](https://testnet.cubescan.network/address/0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0)

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/258
- (pfs)
- (dfe)

**Comment by guidiaz** [comment]
Price poller bot config on Cube Testnet:
```
name = "cube.testnet"
from = "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
provider = "http://gateway:8522"
provider_poa = true
symbol = "CUBET"
evm_finalization_secs = 30
evm_waiting_timeout_secs = 60
evm_polling_latency_secs = 6
witnet_toolkit_timeout_secs = 30
```

**Comment by guidiaz** [comment]
Cube Testnet RPC gateway config:
```
ETHERS_ESTIMATE_GAS_LIMIT: "true"
ETHERS_ESTIMATE_GAS_PRICE: "true"
ETHERS_GAS_PRICE: 50000000000
EVM_CALL_INTERLEAVE_BLOCKS: 5
PORT: 8522
PROVIDER_URL: "https://http-testnet.cube.network"
```

**Comment by guidiaz** [comment]
Price poller bot is now activated for Cube Testnet.

**Comment by guidiaz** [comment]
Change request on docs for publishing Cube EVM testnet addresses and first pfs

**Comment by guidiaz** [comment]
**Cube Mainnet**:

- RPC: https://t.co/xjDiEyBByv
- Chain id: 1818
- Currency symbol: CUBE
- Explorer: https://cubescan.network

**Comment by aesedepece** [comment]
We're live on testnet already. Kudos @guidiaz !
