### ISSUE TITLE
Assess chain integration with Meter.io

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#255]
https://docs.meter.io/

**Comment by aesedepece** [comment]
Testnet:
- Network name: Meter Testnet
- RPC URL: https://rpctest.meter.io
- Chain ID: 83
- Currency symbol: MTR
- Explorer URL: https://scan.meter.io/tx/<tx_id>

**Comment by aesedepece** [comment]
Meter testnet faucet at https://faucet-warringstakes.meter.io/

**Comment by aesedepece** [comment]
Deploy WSB v0.5.6 on **Meter Testnet** (https://github.com/witnet/witnet-solidity-bridge/pull/257):

- **Witnet Solidity Bridge**:
    * **WitnetDecoderLib**: [`0xa3ff5E5af8e54bDf894dA2F6f737cc794bd527C3`](https://scan-warringstakes.meter.io/address/0xa3ff5E5af8e54bDf894dA2F6f737cc794bd527C3)
    * **WitnetParserLib**: [`0x3a46EF336f619e69dcDCa36A6772596E0fD800B3`](https://scan-warringstakes.meter.io/address/0x3a46EF336f619e69dcDCa36A6772596E0fD800B3)
    * **WitnetProxy**: [`0xF99883aa51Fb76E37De6aC37854230d2337D2752`](https://scan-warringstakes.meter.io/address/0xF99883aa51Fb76E37De6aC37854230d2337D2752)
    * **WitnetRequestBoardTrustableDefault**: [`0xCd4D275f88d526959D69107BB4f9FB16c5B95a9b`](https://scan-warringstakes.meter.io/address/0xCd4D275f88d526959D69107BB4f9FB16c5B95a9b)
  
  - **Witnet use cases**:
    * **WitnetPriceRouter**: [`0xBbDB82a16d7b66bb076879f766042b914F1C7572`](https://scan-warringstakes.meter.io/address/0xBbDB82a16d7b66bb076879f766042b914F1C7572)
    * **WitnetRandomness**: [`0x89de43D6295D960Af1F2029a66CE680c7f798fC1`](https://scan-warringstakes.meter.io/address/0x89de43D6295D960Af1F2029a66CE680c7f798fC1)

**Comment by aesedepece** [comment]
All contracts above have been verified through Sourcify.

**Comment by guidiaz** [comment]
Preparing pfs: MTR/USDT-6 and MTRG/USDT-6

**Comment by aesedepece** [comment]
> Preparing pfs: MTR/USDT-6 and MTRG/USDT-6

Thanks sir!

**Comment by guidiaz** [comment]
> * Explorer URL: https://scan.meter.io/tx/<tx_id>

Actual explorer for testnet: https://scan-warringstakes.meter.io/

**Comment by guidiaz** [comment]
Witnet Router on Meter Testnet has been updated to attended these new pfs.

**Comment by guidiaz** [comment]
Pfs contracts presumably verified in sourcify. Perhaps it takes sometime before verification is noticed on the testnet explorer.

**Comment by aesedepece** [comment]
Now that the price feeds are live and the DFE and docs already list the relevant info, we can consider this done. Thanks a lot for your support @guidiaz
