### ISSUE TITLE
Verify latest Solidity deployments

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#259]
and revisit DFE links and addresses within docs:

- WRB v0.5.7
  - [x] Ethereum Mainnet
  - [x] Meter Mainnet (partially)
  - [x] Cube Testnet (partially)
- WC3 contracts:
  - [x] Ethereum Mainnet (multi-part)
  - [x] Polygon Mainnet (multi-part)
  - [x] Conflux eSpace Mainnet (flattened)
  - [x] Cronos Mainnet (multi-part)
  - [x] KCC Mainnet (flattened)
  - [x] Meter Mainnet (multi-part, partially)
  - [x] Metis Andromeda (flattened)
  - [ ] OKXChain Mainnet (not yet possible)

**Comment by guidiaz** [comment]
Adding entries in https://hackmd.io/SWjC53FcR46SNYQDTsDqfA to:
- [x] Meter Testnet
- [ ] Meter Mainnet
- [ ] Cube Testnet

**Comment by guidiaz** [comment]
On **Meter Mainnet**:
- Managed to verify: WitnetDecoderLib, WitnetParserLib, WitnetProxy, WRBTrustableDefault, WitnetPriceFeed
- Failed to verify: WitnetPriceRouter, WitnetRandomness. Getting a "Network error" message. Asked for help to Meter support team.

**Comment by guidiaz** [comment]
On **OKXChain Mainnet**:
- Wc3* contracts cannot get verified because verification form at https://www.oklink.com/ doesn't support Solc v0.8.15 compiler just yet.

**Comment by guidiaz** [comment]
Created change request upon docs site for:
- Adding addresses and pfs on Meter Mainnet

**Comment by aesedepece** [comment]
> Created change request upon docs site for:
> 
>     * Adding addresses and pfs on Meter Mainnet

Merged!

**Comment by guidiaz** [comment]
OpenSea listings:
- Ethereum Mainnet: https://opensea.io/collection/witty-creatures-ethcc5
- Polygon Mainnet: https://opensea.io/collection/witty-creatures-ethcc5-polygon

**Comment by guidiaz** [comment]
TofuNFT listing requires at least 3 tokens on sale or auction. At the moment of writing, only 1 token has been minted on Cronos. None yet on Kcc, Meter, Metis, OKXChain.

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/otherplane/witty-creatures-3.0/pull/74
- https://github.com/witnet/witnet-solidity-bridge/pull/260

**Comment by guidiaz** [comment]
TofuNFT submitted forms:
- [x] Cronos
- [ ] KCC
- [ ] Meter
- [ ] Metis
- [ ] OKXChain

**Comment by guidiaz** [comment]
On **Meter Mainnet**:
- Trying to verify by using https://sourcify.dev/#/verifier, but keep getting "Unexpected token < at position 0" all the time", no matter if following multi-part files, or single flattened file.
- Surprisingly, despite this misleading error, the WitnetRandomness, WitnetPriceRouter and Wc3Token were actually verified at some poing:
  - WitnetPriceRouter: https://scan.meter.io/address/0xA0Ea8C99159843afdAE9eD092E8eaec0368e8A20
  - WitnetRandomess: https://scan.meter.io/address/0xE189B1D26dAAB45cd344452f29Db8E93B5C7FaF1
  - Wc3Token: https://scan.meter.io/address/0xa93bC4a3f5D05b4E825Aa2C7E28d164F831ed3c3

**Comment by guidiaz** [comment]
Enabling ETH/USD-6 at Ethereum Mainnet, on both DFE and DFM:
- https://github.com/witnet/data-feeds-explorer/pull/226
