### ISSUE TITLE
Create RFC on sustainable decentralized bridging model between Witnet and WRB

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#263]

**Comment by guidiaz** [comment]
https://github.com/witnet/witnet-solidity-bridge/discussions/267

**Comment by guidiaz** [comment]
Referred from RFC also on witnet/witnet-rust: https://github.com/witnet/witnet-rust/discussions/2255

**Comment by aesedepece** [comment]
Thanks sir
