### ISSUE TITLE
Deploy on Cube mainnet

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-solidity-bridge#270]
- [x] Fill [form](https://docs.google.com/forms/d/e/1FAIpQLSdNv-LWkj_RW75SHQl2B5rQjdk-ArE_HIfCPd9qc_LcIPUNmQ/viewform)
- [x] Wait for feedback and whitelisting from Cube team
- [x] Buy $CUBE and deposit
- [x] Deploy

**Comment by guidiaz** [comment]
Looks like we've been white-listed, so proceeding to deployment as usual

**Comment by guidiaz** [comment]
**Cube Mainnet**:
- **Witnet Solidity Bridge**:
  * WitnetDecoderLib: [`0x400DbF3645b345823124aaB22D04013A46D9ceD5`](https://cubescan.network/address/0x400DbF3645b345823124aaB22D04013A46D9ceD5)
  * WitnetParserLib:  [`0x1D9c4a8f8B7b5F9B8e2641D81927f8F8Cc7fF079`](https://cubescan.network/address/0x1D9c4a8f8B7b5F9B8e2641D81927f8F8Cc7fF079) 
 * WitnetProxy:  [**`0xd653fbd7c736838289262F0F41A458f35393C88a`**](https://cubescan.network/address/0xd653fbd7c736838289262F0F41A458f35393C88a)
 * WitnetRequestBoardTrustableDefault: [`0x916aC9636F4Ea9f54f07c9De8fDCd828e1b32c9B`](https://cubescan.network/address/0x916aC9636F4Ea9f54f07c9De8fDCd828e1b32c9B)
- **Witnet use cases**:
   * WitnetPriceRouter: [**``**](https://cubescan.network/address/)
   * WitnetRandomness: [**``**](https://cubescan.network/address/)

**Comment by guidiaz** [comment]
Contracts verification not yet possible at https://www.cubescan.network/en-us/verify-contract-solc: `"Invalid licenseType"`

**Comment by guidiaz** [comment]
Setting `0xBCBf910720e52bc4DC269ec37C13aEaa40645721` as authorized reporter address:
- https://www.cubescan.network/en-us/tx/0x9d73e169c6f93a355ac336829cedcae7c78066d560d9979a1dc01ff5dd2a6efb

**Comment by guidiaz** [comment]
Related PRs:
- Solidity: 
- Pfs: 
- DFE: https://github.com/witnet/data-feeds-explorer/pull/235

**Comment by guidiaz** [comment]
Funding bridge evm address:
- https://www.cubescan.network/en-us/tx/0xe88dc2a61ea00d3c36368957fca631f1e86ee6f124c634c279f277f46e327945

**Comment by guidiaz** [comment]
Published price feeds:
- https://feeds.witnet.io/cube

**Comment by guidiaz** [comment]
Create change request on https://docs.witnet.io as to include cube mainnet addresses and pfs.

**Comment by aesedepece** [comment]
> Create change request on https://docs.witnet.io as to include cube mainnet addresses and pfs.

Merged!

**Comment by Tommytrg** [comment]
https://feeds.witnet.io/cube/cube-mainnet_btc-usd_6
