### ISSUE TITLE
Deploy on SysCoin testnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#273]
- Expecting no major obstacle for integration
- Deploy and publish first pfs:
  - [x] SYS/USDT-6 ?
  - [ ] USDT/USD-6 ?
  - [ ] SYS/USD-6 ??

**Comment by guidiaz** [comment]
Syscoin is a Proof-of-Work blockchain, [merged-mined](https://docs.syscoin.org/docs/tech/merged-mining) with Bitcoin. At its base it is a dual-layered blockchain: the core is the Syscoin blockchain itself, and running in tandem with it is an Ethereum Virtual Machine (EVM) layer called [NEVM](https://docs.syscoin.org/docs/tech/nevm) (Network-Enhanced Virtual Machine), which provides smart contract functionality.

**Comment by guidiaz** [comment]
Syscoin is designed to be a settlement layer for zkRollups and other L2s/execution layers, as such it has a 2.5 minute block time for the optimal settlement security, it is advised to create dApps using zkRollups rather than using the Syscoin blockchain itself for executing smart contracts. You can find zkRollup resources [here](https://docs.syscoin.org/docs/dev-resources/nevm/zk-rollups).

**Comment by guidiaz** [comment]
Syscoin's NEVM Testnet is called Tanenbaum

**Comment by guidiaz** [comment]
Tanenbaum faucet requires tweeting the address to be fed

**Comment by guidiaz** [comment]
Asked Syscoin <> Pegasys <> Witnet group for at least 2 tSYS, as transactions shown at https://tanenbaum.io/ seem to be using a gas price of 10 gwei

**Comment by guidiaz** [comment]
Tried to deploy w/ just 0.01 tsys, but getting this error from the rpc provider at https://rpc.tanenbaum.io: "transaction type not supported".
Perhaps, it's just because there's not enough balance.

**Comment by guidiaz** [comment]
Got 10 tSYS.

**Comment by guidiaz** [comment]
Syscoin rpc provider only accept type 0x2 txs (eip-1559)

**Comment by guidiaz** [comment]
Deployed and verified on **Syscoin Testnet**:
  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb`](https://tanenbaum.io/address/0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb)
    * WitnetParserLib: [`0x7D8A488BACB56dA2De17628e26a21fFd97792b81`](https://tanenbaum.io/address/0x7D8A488BACB56dA2De17628e26a21fFd97792b81)
    * WitnetProxy: [**`0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431`**](https://tanenbaum.io/address/0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431)
    * WitnetRequestBoardTrustableDefault: [`0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0`](https://tanenbaum.io/address/0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0)

**Comment by guidiaz** [comment]
average block time in syscoin is 2.4 minutes

**Comment by guidiaz** [comment]
aparently, two confirmation blocks on the rpc provider side seem to be set, making tx receipts take up to 500 secs to be generated

**Comment by guidiaz** [comment]
See related PRs:
- w3gw
- solidity
- pfs
- dfe

**Comment by guidiaz** [comment]
Set `0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77` as authorized reporter. Funded w/ 1 tSYS:
- https://tanenbaum.io/address/0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77

**Comment by guidiaz** [comment]
Deployed `bridgesyscointestnet` stack on bootstrap node.

**Comment by guidiaz** [comment]
Pfs poller params:
```
  WPFP_NETWORK_NAME: "syscoin.testnet"
  WPFP_WEB3_FINALIZATION_SECS: 480
  WPFP_WEB3_FROM: "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
  WPFP_WEB3_PROVIDER_POA: "true"
  WPFP_WEB3_PROVIDER_WAITING_TIMEOUT_SECS: 480
  WPFP_WEB3_PROVIDER_POLLING_LATENCY_SECS: 15
  WPFP_WEB3_SYMBOL: "tSYS"
  WPFP_WITNET_TOOLKIT_TIMEOUT_SECS: 15
```

**Comment by guidiaz** [comment]
W3gw params:
```
  ETHERS_ESTIMATE_GAS_PRICE: "true"
  ETHERS_ESTIMATE_GAS_LIMIT: "true"
  ETHERS_FORCE_EIP_1559: "true"
  PROVIDER_URL: "https://rpc.tanenbaum.io"
```

**Comment by guidiaz** [comment]
Bridge params:
``` 
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_ACCOUNT: "0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77"
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_GAS_LIMITS: "report_result = 3_000_000"
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_NUM_CONFIRMATIONS: 0
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WRB_CONTRACT_ADDR: "0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431"
```

**Comment by guidiaz** [comment]
Create change request for publishing addresses and pfs on https://docs.witnet.io

**Comment by guidiaz** [comment]
https://feeds.witnet.io/syscoin

**Comment by aesedepece** [comment]
> Create change request for publishing addresses and pfs on https://docs.witnet.io

Merged! We can now consider this done!
