### ISSUE TITLE
Deploy on Optimism Testnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#274]
- Most probably, a new rpc-gateway may be required as to properly estimate a tx's gas price (and limit)
- Perhaps (unprobable), some specific implementation of WitnetRequestBoard contract may be required
- Deploy and publish first pfs:
  - [x] OP/USDT-6 ?
  - [ ] USDT/USD-6 ?
  - [ ] OP/USD-6 ??

**Comment by guidiaz** [comment]
https://community.optimism.io/docs/developers/

**Comment by guidiaz** [comment]
Bridging 1 ETH from Ethereum Goerli to Optimism Goerli:
- https://goerli.etherscan.io/tx/0x9e81427cf2e00dd81c989e2608a90c85d17976df34f73ba4181847fa3ac23dd6

**Comment by guidiaz** [comment]
On WitnetRequestBoardTrustableOvm2 implementation, assessing how to better estimate report reward by interacting w/ pre-compiled `OVM_GasPriceOracle` contract at L2

**Comment by guidiaz** [comment]
Funding 0.2 oETH to bridge evm address:
- https://blockscout.com/optimism/goerli/tx/0x87a888851fa72414336c73d8377f75fe291247ff4f54b10fa403fb70f3c366f8/internal-transactions

**Comment by guidiaz** [comment]
Setting `0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77` as authorized reporter in the WRB.

**Comment by guidiaz** [comment]
Deployed and verified Witnet Solidity Bridge contracts on **Optimism Goerli**:
  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x7D8A488BACB56dA2De17628e26a21fFd97792b81`](https://blockscout.com/optimism/goerli/address/0x7D8A488BACB56dA2De17628e26a21fFd97792b81)
    * WitnetParserLib: [`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`](https://blockscout.com/optimism/goerli/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)
    * WitnetProxy: [**`0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb`**](https://blockscout.com/optimism/goerli/address/0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb)
    * WitnetRequestBoardTrustableOvm2: [`0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d`](https://blockscout.com/optimism/goerli/address/0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d)

 - **Witnet use cases**:
    * WitnetPriceRouter: [**`0xD9465D38f50f364b3263Cb219e58d4dB2D584530`**](https://blockscout.com/optimism/goerli/address/0xD9465D38f50f364b3263Cb219e58d4dB2D584530)
    * WitnetRandomness: [**`0x9E943Ab1FD0D35B3BaDe31AA78D60C485EA1a604`**](https://blockscout.com/optimism/goerli/address/0x9E943Ab1FD0D35B3BaDe31AA78D60C485EA1a604)

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/web3-jsonrpc-gateway/pull/41
- https://github.com/witnet/witnet-solidity-bridge/pull/280
- pfs
- dfe

**Comment by guidiaz** [comment]
Created `bridgeoptimismgoerli` stack on bootstrap host

**Comment by guidiaz** [comment]
rpc gateway config:
```
  EVM_CALL_INTERLEAVE_BLOCKS: 2
  ETHERS_ESTIMATE_GAS_PRICE: "true"
  ETHERS_ESTIMATE_GAS_LIMIT: "true"
  ETHERS_GAS_LIMIT_FACTOR: 1.25
  ETHERS_MOCK_FILTERS: "true"
```

**Comment by guidiaz** [comment]
poller bot config:
```
```

**Comment by guidiaz** [comment]
bridge base config:
```
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_ACCOUNT: "0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77"
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_GAS_LIMITS: "report_result = 6_000_000"
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_NUM_CONFIRMATIONS: 3
  WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WRB_CONTRACT_ADDR: "0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb"
```

**Comment by aesedepece** [comment]
> Related PRs:
> 
>     * [feat: add ethers support to Optimism web3-jsonrpc-gateway#41](https://github.com/witnet/web3-jsonrpc-gateway/pull/41)
> 
>     * [feat: add support to optimism #280](https://github.com/witnet/witnet-solidity-bridge/pull/280)
> 
>     * [feat: add support to optimism witnet-price-feeds#133](https://github.com/witnet/witnet-price-feeds/pull/133)
> 
>     * [feat: add support to optimism data-feeds-explorer#245](https://github.com/witnet/data-feeds-explorer/pull/245)

All approved!

**Comment by guidiaz** [comment]
https://feeds.witnet.io/optimism

**Comment by guidiaz** [comment]
created change request on https://docs.witnet.io
