### ISSUE TITLE
Deploy on Arbitrum Testnets

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#288]
https://developer.arbitrum.io/intro/

**Comment by guidiaz** [comment]
The fact that multiple chains can run in parallel is a crucial perk to off-chain scaling technology. Currently, on Ethereum mainnet, there are 2 Arbitrum chains: one Arbitrum Rollup chain, called ["Arbitrum One,"](https://portal.arbitrum.one/) and one AnyTrust chain, called ["Nova"](https://nova.arbitrum.io/); users and developers can pick whatever suits their security / transaction cost needs.

**Comment by guidiaz** [comment]
An Arbitrum AnyTrust chain doesn’t have the same decentralization / trustlessness / permissionless security guarantees of a Rollup chain, and thus can offer lower fees. Rollup and AnyTrust are similar in many ways, though have one key difference: whereas in Rollup, all data is posted on L1 (which allows anyone to permissionless join as a validator), in AnyTrust, data is managed off-chain. In the case of a challenge, an AnyTrust chain reverts back to “rollup mode”; the security assumption here is that at least 2 of the committee members are honest (i.e., they will provide the data when it’s necessary). Keeping the data off-chain in the happy/common case means the system can charge the user significantly lower fees. For applications that require high transaction throughput and don’t require the full decentralization that rollups provide, AnyTrust could be a sensible tradeoff.

**Comment by guidiaz** [comment]
GD: for the time being, we'll just deploy on **Arbitrum One Testnet**, until some specific support is requested for Arbitrum Nova.

**Comment by guidiaz** [comment]
**Arbitrum/Ethereum Differences**:
- Time in L2 is tricky; the timing assumptions one is used to making about L1 blocks don't exactly carry over into the timing of Arbitrum blocks. 
- Arbitrum's L2 block hashes should not be relied on as a secure source of randomness.
- The L2 fees an Arbitrum transaction pays essentially work identically to gas fees on Ethereum. Arbitrum transactions must also, however, pay an L1-fee component to cover the cost of their calldata.
- Arbitrum transaction receipts include two additional fields: `l1BlockNumber`, `gasUdedForL1`.

**Comment by guidiaz** [comment]
**Block numbers and time**:
- Arbitrum blocks are assigned their own L2 block numbers, distinct from Ethereum's L1 block numbers.
- But,,,,,,,,    *accessing block numbers within an Arbitrum smart contract (i.e., block.number in Solidity) will return a value close to (but not necessarily exactly) the L1 block number at which the Sequencer received the transaction.*
- Arbitrum blocks have their own block numbers, starting at 0 at the Arbitrum genesis block and updating sequentially.
- A client that queries an Arbitrum node's RPC interface (for, ie., transaction receipts) will receive the transaction's Arbitrum block number as the standard block number field. The L1 block number will also be included in the added l1BlockNumber field.

**Comment by guidiaz** [comment]
Nitro Goerli Rollup Testnet: This testnet (421613) uses the Nitro rollup tech stack; it is expected to be the primary, stable Arbitrum testnet moving forward. Users can now use [Alchemy](https://alchemy.com/?a=arbitrum-docs), [Infura](https://infura.io/), and [QuickNode](https://www.quicknode.com/) to interact with the Arbitrum One.

**Comment by guidiaz** [comment]
Let's go for **Arbitrum Nitro Goerli" deployment.

**Comment by guidiaz** [comment]
Bridging 0.5 GoerliETH to 0.5 AGOR in Arbitrum Nitro Goerli:
- L1 tx: https://goerli.etherscan.io/tx/0xc2613cc10de0425e8f3aafc2856ea884aa4e19153826d944e853314366714c6c
- L2 tx:

**Comment by guidiaz** [comment]
**Arbitrum Nitro Goerli**:
- Chain id: 421613
- RPC: https://goerli-rollup.arbitrum.io/rpc
- Explorer: https://goerli.arbiscan.io, https://goerli-rollup-explorer.arbitrum.io

**Comment by guidiaz** [comment]
Goerli faucet can be used on ETH/L1, and then bridge those to ARB/ETH/L2 via the **Arbitrum Bridge** dapp:
- https://bridge.arbitrum.io/

(works the same of all Arbitrum chains, as long as they're available on preferred web wallet)

**Comment by aesedepece** [comment]
> **Arbitrum Nitro Goerli**:
> 
>     * Chain id: 421613
> 
>     * RPC: https://goerli-rollup.arbitrum.io/rpc
> 
>     * Explorer: https://goerli.arbiscan.io, https://goerli-rollup-explorer.arbitrum.io

I sent an Infura URL over Telegram, just in case you want to use that!

**Comment by guidiaz** [comment]
Bridging GoerliETH from L1 to L2 takes like 20-30 minutes.

**Comment by guidiaz** [comment]
Script "arbitrum:goerli" added to Web3 RPC gateway. It works seamlessly.

**Comment by guidiaz** [comment]
Deployed and verified contracts in **Arbitrum Nitro Goerli**:

  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x9Ef886Df202100FFc1b38388b3591e0031E53045`](https://goerli.arbiscan.io/address/0x9Ef886Df202100FFc1b38388b3591e0031E53045)
    * WitnetParserLib: [`0x7d0a71D7D797b7b2637F682e4cB47f66602e59F3`](https://goerli.arbiscan.io/address/0x7d0a71D7D797b7b2637F682e4cB47f66602e59F3)
    * WitnetProxy: [`0xa6a6b2cBE9Ce5B8fF94729F1eC402efc5042AbBF`](https://goerli.arbiscan.io/address/0xa6a6b2cBE9Ce5B8fF94729F1eC402efc5042AbBF)
    * WitnetRequestBoardTrustableDefault: [`0x17c7b4E454689EF181dE1FfA6eC59b3D146344bD`](https://goerli.arbiscan.io/address/0x17c7b4E454689EF181dE1FfA6eC59b3D146344bD)

  - **Witnet use cases**:
    * WitnetPriceRouter: [`0xAafb2D27E2E0f83dcE501a2879aaD710ec377403`](https://goerli.arbiscan.io/address/0xAafb2D27E2E0f83dcE501a2879aaD710ec377403)
    * WitnetRandomness: [`0xB0C5d40A7658b2ab28360aFa6eB5bAeb2fFe86c3`](https://goerli.arbiscan.io/address/0xB0C5d40A7658b2ab28360aFa6eB5bAeb2fFe86c3)
  
  - **Witnet price feeds**:
    * Price-ETH/USD-6: [``](https://goerli.arbiscan.io/address/)

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/296
- https://github.com/witnet/witnet-price-feeds/pull/145
- https://github.com/witnet/data-feeds-explorer/pull/271

**Comment by guidiaz** [comment]
Both evm accounts for pollers and bridges have been authorized.

**Comment by guidiaz** [comment]
Create new bridge stack in bootstrap host, named as "**bridgearbitrumgoerli**".

**Comment by guidiaz** [comment]
Created change request on https://docs.witnet.io.
