### ISSUE TITLE
Deploy on Boba Beam testnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#289]
https://docs.boba.network/for-developers/network-moonbeam#bobabase-l2-1297-for-the-moonbase-testnet-1287

**Comment by guidiaz** [comment]
Boba L2 testnet is rolled up into Moonbase Alpha, being known as "Bobabase"

**Comment by guidiaz** [comment]
**Bobabase** links and endpoints:
- Chain id: 1297
- RPC: https://bobabase.boba.network
- Replica RPC: https://replica.bobabase.boba.network
- Gateway: https://gateway.bobabase.boba.network
- Blockexplorer: https://blockexplorer.bobabase.boba.network

**Comment by guidiaz** [comment]
Bridging 1 DEV to Bobabase:
- https://moonbase.moonscan.io/tx/0xbe56aec04c3b9697563f7e51ce14d2538bdca8bf1dadad1419354dd91419e360

**Comment by guidiaz** [comment]
> Bobabase gas can be either paid with oDEV (Moonbase) or Boba token at Bobabase.

However, Metamask is showing Boba balance on Bobabase ... let's try to deploy w/ 10 Boba retrieved from test token faucet , and see if internal native transfers between contracts are actually paid w/ Boba instead of oDev (in the contrary to what happens in Boba/Ethereum) ...

**Comment by guidiaz** [comment]
Bobabase's block explorer fails when trying to verify a contract:
- https://blockexplorer.bobabase.boba.network/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425/contract_verifications/new

**Comment by guidiaz** [comment]
Deployed but unverified contracts in **Bobabase**:
  - **Witnet Solidity Bridge**:
    - WitnetDecoderLib: [`0x7D8A488BACB56dA2De17628e26a21fFd97792b81`](https://blockexplorer.bobabase.boba.network/address/0x7D8A488BACB56dA2De17628e26a21fFd97792b81)
    - WitnetParserLib: [`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`](https://blockexplorer.bobabase.boba.network/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)
    - WitnetProxy: [`0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb`](https://blockexplorer.bobabase.boba.network/address/0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb)
    - WitnetRequestBoardTrustableDefault: [`0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d`](https://blockexplorer.bobabase.boba.network/address/0xD9a6d1Ea0d0f4795985725C7Bd40C31a667c033d)

  - **Witnet use cases**:
    - WitnetPriceRouter: [`0xD9465D38f50f364b3263Cb219e58d4dB2D584530`](https://blockexplorer.bobabase.boba.network/address/0xD9465D38f50f364b3263Cb219e58d4dB2D584530)
    - WitnetRandomness: [`0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f`](https://blockexplorer.bobabase.boba.network/address/0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f)

**Comment by guidiaz** [comment]
Create new bridge stack in bootstrap host, named as "bridgebobabase".

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/data-feeds-explorer/pull/270
- https://github.com/witnet/witnet-solidity-bridge/pull/294
- https://github.com/witnet/witnet-price-feeds/pull/144

**Comment by guidiaz** [comment]
Created change request on https://docs.witnet.io for refactoring previously supported boba networks and pf links.

**Comment by guidiaz** [comment]
Created another change request on https://docs.witnet.io for adding support to **Bobabase** tesntet.

**Comment by aesedepece** [comment]
Changes to the documentation are merged now!

**Comment by guidiaz** [comment]
Using BOBA as gas fee token seems to work totally seamlessly. Let's then test to upgrade the WRB w/ WRBTrustableOvm2 that was proven to work on Optimism ETH/L2:
    - **WitnetRequestBoardTrustableOvm2**: [`0xE4cFf55F193b3493F1Aa6811738309b2ACf6C963`](https://blockexplorer.bobabase.boba.network/address/0xE4cFf55F193b3493F1Aa6811738309b2ACf6C963)

**Comment by guidiaz** [comment]
Funding bridge evm account by sending 1 tBOBA to `0x8c49cafc4542d9ea9107d4e48412aced2a68aa77`:
- https://blockexplorer.bobabase.boba.network/tx/0x13cb17e91462e83becb66e6d029e476cabeca4c03c7a278790cdc933f18f7403

**Comment by guidiaz** [comment]
Authorizing bridge evm account:
- https://blockexplorer.bobabase.boba.network/tx/0xfe1fee9fd0ec2a488944990156e7e7b6c6f3b981c6ae18632089facab3f09608

**Comment by guidiaz** [comment]
Apparently, by setting poller and bridge evm accounts to use Boba as gas fee token, transfer back mechanism implemented at WitnetRandomnes seems to work, as poller evm balance decrease in proportion to cost of randomization fee, and not to `msg.value` being sent upon `randomize()`.

**Comment by guidiaz** [comment]
Before eventually deploying on Bobabeam (mainnet), we'll need to double check that Bobabase's evm account on bridge maintains healthy balance.

**Comment by aesedepece** [comment]
We can consider this done now.
