### ISSUE TITLE
Deploy on Dogechain mainnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#291]
Metamask:
- Rpc provider: https://rpc01-sg.dogechain.dog
- Chain id: 2000
- Symbol: wDOGE
- Explorer URL: https://explorer.dogechain.dog

**Comment by guidiaz** [comment]
Deployed and verified contracts in **Dogechain Mainnet**:

  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x1ebD93231a7fE551E1d6405404Df34909eff4c2C`](https://explorer.dogechain.dog/address/0x1ebD93231a7fE551E1d6405404Df34909eff4c2C)
    * WitnetParserLib:  [`0xD39D4d972C7E166856c4eb29E54D3548B4597F53`](https://explorer.dogechain.dog/address/0xD39D4d972C7E166856c4eb29E54D3548B4597F53)
    * WitnetProxy:  [**`0xF2712e7114A237625EFC8bBA6a6ed1Bb8b6029c9`**](https://explorer.dogechain.dog/address/0xF2712e7114A237625EFC8bBA6a6ed1Bb8b6029c9)
    * WitnetRequestBoardTrustableDefault: [`0x8555fF5b5A370FEF73Ce723b3fFfC57c161a1945`](https://explorer.dogechain.dog/address/0x8555fF5b5A370FEF73Ce723b3fFfC57c161a1945)

  - **Witnet use cases**:
    * WitnetPriceRouter: [**`0xD7f7933992c25A504e9Ddf7e76a3c1D6c432b25D`**](https://explorer.dogechain.dog/address/0xD7f7933992c25A504e9Ddf7e76a3c1D6c432b25D)
    * WitnetRandomness: [**`0x7FdB9CDe98967140a5627dA5221DBC03Bd8e8ad5`**](https://explorer.dogechain.dog/address/0x7FdB9CDe98967140a5627dA5221DBC03Bd8e8ad5)

**Comment by guidiaz** [comment]
For some unknown reason, WitnetRandomness cannot get verified due to bytecode mistmatch.

**Comment by guidiaz** [comment]
Funding bridge evm account:
- https://explorer.dogechain.dog/tx/0x3b2b860272408ff760d29458ca6b3af6f4d156963969559d7af19082591fbef1

**Comment by guidiaz** [comment]
Authorizing bridge evm account:
- https://explorer.dogechain.dog/tx/0x924781e2b9efd006de9e2f3be977952e963f218f6699217679f91018fcfacf98

**Comment by guidiaz** [comment]
Created new bridge stack for **Dodechain Mainnet**:
```
EVM_CALL_INTERLEAVE_BLOCKS: 2
ETHERS_ESTIMATE_GAS_PRICE: "true"
ETHERS_ESTIMATE_GAS_LIMIT: "true"
ETHERS_GAS_PRICE: 500000000000
PROVIDER_URL: "https://dogechain.ankr.com"
```

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/292
- https://github.com/witnet/witnet-price-feeds/pull/143
- https://github.com/witnet/data-feeds-explorer/pull/269

**Comment by guidiaz** [comment]
Submitted change request on https://docs.witnet.io

**Comment by aesedepece** [comment]
> Submitted change request on https://docs.witnet.io

Merged!
