### ISSUE TITLE
Deploy on Boba Goerli

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#302]
Boba Goerli ChainID: 2888
Boba Goerli RPC: [https://goerli.boba.network](https://goerli.boba.network)             
Boba Goerli Tokens Gateway: [https://gateway.goerli.boba.network](https://gateway.goerli.boba.network)       
Boba Goerli Blockexplorer: [https://testnet.bobascan.com](https://testnet.bobascan.com)

**Comment by guidiaz** [comment]
Bridging 0.2 goETH/L1 to goETH/L2:
- https://goerli.etherscan.io/tx/0x5f8d0b83c59268edb00f9217a864c0054c4cca641179f5a93ebb279e9d79c4d4

**Comment by guidiaz** [comment]
In order to change fee currency to Boba on L2, at least 3.0 BOBA/L2 is required, so we'll stick to goETH/L2 for deployments and price updates.

**Comment by guidiaz** [comment]
Deployed and verified contracts:
  - **Witnet Solidity Bridge**:
    - WitnetDecoderLib: [`0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb`](https://testnet.bobascan.com/address/0x0985FDe9f424fe4f5AC516F66bAf5591e18aCBEb)
    - WitnetParserLib: [`0x7D8A488BACB56dA2De17628e26a21fFd97792b81`](https://testnet.bobascan.com/address/0x7D8A488BACB56dA2De17628e26a21fFd97792b81)
    - WitnetProxy: [`0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431`](https://testnet.bobascan.com/address/0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431)
    - WitnetRequestBoardTrustableOvm2: [`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`](https://testnet.bobascan.com/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)

  - **Witnet use cases**:
    - WitnetPriceRouter: [`0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f`](https://testnet.bobascan.com/address/0xB4B2E2e00e9d6E5490d55623E4F403EC84c6D33f)
    - WitnetRandomness: [`0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0`](https://testnet.bobascan.com/address/0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0)

**Comment by guidiaz** [comment]
Created testnet stack on bootstrap machine. No poller yet.

**Comment by guidiaz** [comment]
Sent 0.08 goETH/L2 to bridge evm address:
- https://testnet.bobascan.com/tx/0xbd9599d0397a5aa95384039227ab154d4d688191f2af0a77ccb8fc3f872ec7a2

**Comment by guidiaz** [comment]
Testing WitnetRandomness:
- https://testnet.bobascan.com/tx/0xcca8af3b2e6940c898ac32354da119e71f1e61bd94d89d8e87e81e67eea91c73
- https://witnet.network/search/20ba0cdb5029857fd329ea826d2ce8514891bcaa38b3ecd99a47dffe0a34b131

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/303
- https://github.com/witnet/witnet-price-feeds/pull/162
- https://github.com/witnet/data-feeds-explorer/pull/281

**Comment by guidiaz** [comment]
Deployed and verified price feeds:
  - **Witnet price feeds**:
    - BobaUsdtPriceFeed: [`0x4092CC222B1bD1176D8a8cBE4070ccea66E9d1D6`](https://testnet.bobascan.com/address/0x4092CC222B1bD1176D8a8cBE4070ccea66E9d1D6)
    - DaiUsdPriceFeed: [`0x04120cea2FBE03accccEd42e0d9334323F173857`](https://testnet.bobascan.com/address/0x04120cea2FBE03accccEd42e0d9334323F173857)
    - FraxUsdtPriceFeed: [`0x502792a6dc858925e9Fb0c3E730411AEb5bB2c4A`](https://testnet.bobascan.com/address/0x502792a6dc858925e9Fb0c3E730411AEb5bB2c4A)
    - OloUsdcPriceFeed: [`0xa0a6c0Ef4Fa60E380Ce28A5e3Ce74508E884a537`](https://testnet.bobascan.com/address/0xa0a6c0Ef4Fa60E380Ce28A5e3Ce74508E884a537)

**Comment by guidiaz** [comment]
Poller is now up and running.

**Comment by guidiaz** [comment]
Created change request on https://docs.witnet.io

**Comment by aesedepece** [comment]
I think we can close this.
