### ISSUE TITLE
Deploy on Scroll Testnet

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-solidity-bridge#304]
https://prealpha.scroll.io/

**Comment by guidiaz** [comment]
Got 1 tsETH from faucet on L1/Testnet

**Comment by guidiaz** [comment]
Bridged 0.99 tsETH from L1/Testnet to L2/Testnet:
- https://l1scan.scroll.io/tx/0x5826002faaea693013897037ade854fd5cfd57f451222ff6fc9dbe381d548084

**Comment by guidiaz** [comment]
Transferring 0.1 tsETH to bridge account on L2/Testnet:
- https://l2scan.scroll.io/tx/0x770776320615fd6dacc005b8428f8144c5cab115524afda0cf14d839329d2621

**Comment by guidiaz** [comment]
RPC/L2 endpoint is timing out too much frequently:
`Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":935,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="https://prealpha.scroll.io/l2", code=TIMEOUT, version=web/5.7.1)`

**Comment by guidiaz** [comment]
So far deployed contracts:
  - **Witnet Solidity Bridge**:
    * WitnetParserLib: [`0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0`](https://l2scan.scroll.io/address/0xeD074DA2A76FD2Ca90C1508930b4FB4420e413B0)
    * WitnetProxy: [`0x02Cd4089679EAA9431a88170fd784e7dE78A2425`](https://l2scan.scroll.io/address/0x02Cd4089679EAA9431a88170fd784e7dE78A2425)
    * WitnetRequestBoardTrustableDefault: [`0x56834Ff8D4b27db647Da97CA3bd8540f7fA0e89D`](https://l2scan.scroll.io/address/0x56834Ff8D4b27db647Da97CA3bd8540f7fA0e89D)
    
  - **Witnet use cases**:
    * WitnetPriceRouter: [``](https://l2scan.scroll.io/address/)
    * WitnetRandomness: [``](https://l2scan.scroll.io/address/)

**Comment by guidiaz** [comment]
Testing randomness:
- https://l2scan.scroll.io/tx/0xdeb5fa415029f856ad85b38e32bd9dd959cfdf79cf3b8980e6281e0ff203be4b

**Comment by guidiaz** [comment]
Deployed and verified price feeds:
* Price-BTC/USD-6: [`0xa0a6c0Ef4Fa60E380Ce28A5e3Ce74508E884a537`](https://l2scan.scroll.io/address/0xa0a6c0Ef4Fa60E380Ce28A5e3Ce74508E884a537)
* Price-ETH/USD-6: [`0xAf89a59876145202a027E73340592F05B28A6D99`](https://l2scan.scroll.io/address/0xAf89a59876145202a027E73340592F05B28A6D99)
* Price-UNI/USD-6: [`0x0C4be6AA667df48de54BA174bE7948875fdf152B`](https://l2scan.scroll.io/address/0x0C4be6AA667df48de54BA174bE7948875fdf152B)
* Price-USDC/USD-6: [`0xd63844c34Ec560627c1d793Ac685aD8Ce43C4DdC`](https://l2scan.scroll.io/address/0xd63844c34Ec560627c1d793Ac685aD8Ce43C4DdC)

**Comment by guidiaz** [comment]
New price feeds published on DFE:
- https://feeds.witnet.io/scroll

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/305
- https://github.com/witnet/witnet-price-feeds/pull/165
- https://github.com/witnet/data-feeds-explorer/pull/284

**Comment by guidiaz** [comment]
Created change request on https://docs.witnet.io
