### ISSUE TITLE
Deploy on Ultron Mainnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#306]

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/305
- pfs
- dfe
- iac

**Comment by guidiaz** [comment]
WRB v0.6.1 contracts:
  - **Witnet Solidity Bridge**:
    * WitnetDecoderLib: [`0x400DbF3645b345823124aaB22D04013A46D9ceD5`](https://ulxscan.com/address/0x400DbF3645b345823124aaB22D04013A46D9ceD5)
    * WitnetParserLib: [`0x1D9c4a8f8B7b5F9B8e2641D81927f8F8Cc7fF079`](https://ulxscan.com/address/0x1D9c4a8f8B7b5F9B8e2641D81927f8F8Cc7fF079)
    * WitnetProxy: [`0xd653fbd7c736838289262F0F41A458f35393C88a`](https://ulxscan.com/address/0xd653fbd7c736838289262F0F41A458f35393C88a)
    * WitnetRequestBoardTrustableDefault: [`0xE22f48DDdcb34BD34489fE224d7fFC1b0a361D87`](https://ulxscan.com/address/0xE22f48DDdcb34BD34489fE224d7fFC1b0a361D87)

 - **Witnet use cases**:
    * WitnetPriceRouter: [`0xD39D4d972C7E166856c4eb29E54D3548B4597F53`](https://ulxscan.com/address/0xD39D4d972C7E166856c4eb29E54D3548B4597F53)
    * WitnetRandomness: [`0x1ebD93231a7fE551E1d6405404Df34909eff4c2C`](https://ulxscan.com/address/0x1ebD93231a7fE551E1d6405404Df34909eff4c2C)

> Ultron block explorer doesn't support contract verification just yet.

**Comment by guidiaz** [comment]
Setting `0xbcbf910720e52bc4dc269ec37c13aeaa40645721` as bridge evm account:
- https://ulxscan.com/tx/0xdfa9aa6653aa52e866ac4acab563ff2af7fcda6f7b1db9c122ca7d59b3414c3f
- https://ulxscan.com/transactions/0xe2c1f7d886f682dd6e72fe68420b9c5f127f05db048ba7f50daa9768ba5b8672

**Comment by guidiaz** [comment]
Created change request on https://docs.witnet.io

**Comment by aesedepece** [comment]
We're live now. Thanks @guidiaz @parodyBit
