### ISSUE TITLE
Deploy on Elastos Testnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#314]
https://docs.elastos.net/guides/key-features

**Comment by aesedepece** [comment]
Explorer: https://esc-testnet.elastos.io/

**Comment by guidiaz** [comment]
- RPC provider: https://api-testnet.elastos.io/esc
- Block explorer: https://esc-testnet.elastos.io/
- Chain id: 21
- Faucet: https://esc-faucet.elastos.io/

**Comment by guidiaz** [comment]
Deployed addresses:
  - **Libs**:
    - WitnetEncodingLib: [`0xf6d52770453166de85B6B6260Cf22196bC460E88`](https://esc-testnet.elastos.io/address/0xf6d52770453166de85B6B6260Cf22196bC460E88) 
    - WitnetLib: [`0x1b91eAB33362f10A5F803Fe3f0d181F42caFaac3`](https://esc-testnet.elastos.io/address/0x1b91eAB33362f10A5F803Fe3f0d181F42caFaac3)

  - **Proxies**:
    * Create2Factory: [`0xDe312a6f7fA35320E8DD109c8ea42e82806DC45b`](https://esc-testnet.elastos.io/address/0xDe312a6f7fA35320E8DD109c8ea42e82806DC45b)
    * WitnetBytecodes: [`0x000000b3B867AEF034469bBA55cAD342A4E1A305`](https://esc-testnet.elastos.io/address/0x000000b3B867AEF034469bBA55cAD342A4E1A305)
    * WitnetPriceRouter: [`0xfeeeed88838b4fa4EE46D05c2148e645058f3C28`](https://esc-testnet.elastos.io/address/0xfeeeed88838b4fa4EE46D05c2148e645058f3C28)
    * WitnetRandomness: [`0x123456f4De47e1947210CD62e2f8CF9c2FeD9d4d`](https://esc-testnet.elastos.io/address/0x123456f4De47e1947210CD62e2f8CF9c2FeD9d4d)
    * WitnetRequestBoard: [`0x0000007F26760C151AC86695D5846D21e7828B67`](https://esc-testnet.elastos.io/address/0x0000007F26760C151AC86695D5846D21e7828B67)
    * WitnetRequestFactory: [`0xFaCADE177178C6E0C6914CAe220F2824fF5587B8`](https://esc-testnet.elastos.io/address/0xFaCADE177178C6E0C6914CAe220F2824fF5587B8)
    
  - **Implementations**:
    * WitnetBytecodesImplementation: [`0x4743325168af9195Aa5b25e491E9bE87d87E7F93`](https://esc-testnet.elastos.io/address/0x4743325168af9195Aa5b25e491E9bE87d87E7F93)
    * WitnetPriceRouterImplementation: [`0x4874cb1732eE1167A006E0Ab047D940ACF04D771`](https://esc-testnet.elastos.io/address/0x4874cb1732eE1167A006E0Ab047D940ACF04D771)
    * WitnetProxy: [`0x840bafDC40D88F54Db41327fe1C85241f9151243`](https://esc-testnet.elastos.io/address/0x840bafDC40D88F54Db41327fe1C85241f9151243)
    * WitnetRandomnessImplementation: [`0x6dc0E2AC80550F901cd4d5F5a4C48333A0ca97Ee`](https://esc-testnet.elastos.io/address/0x6dc0E2AC80550F901cd4d5F5a4C48333A0ca97Ee)
    * WitnetRequestBoardImplementation: [`0xB5447342cA17A40e59d410b340ba412E22e36201`](https://esc-testnet.elastos.io/address/0xB5447342cA17A40e59d410b340ba412E22e36201)
    * WitnetRequestFactoryImplementation: [`0xeDA4f244FEe1D6a3EA0fB2c0Fc6b7D1c49fEF01D`](https://esc-testnet.elastos.io/address/0xeDA4f244FEe1D6a3EA0fB2c0Fc6b7D1c49fEF01D)

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/data-feeds-explorer/pull/306
-

**Comment by guidiaz** [comment]
Contracts seem not to be verifiable atm, not via the block explorer, nor the blockscout api at https://esc-testnet.elastos.io/api.

According to support contact in Elastos: "It could be the compiler version. ESC is undergoing an upgrade soon (not sure current status) to jump from constantinople to london EVM version and solidity from 0.7 to 0.8."

**Comment by guidiaz** [comment]
Built and deployed new pfs:
* Price-ELA/USDT-6: [`0x620e20d91C9b0e11ecAE439E7b85138DA2a1003F`](https://esc-testnet.elastos.io/address/0x620e20d91C9b0e11ecAE439E7b85138DA2a1003F)

**Comment by guidiaz** [comment]
Triggering first randomize on WitnetRandomness:
- https://esc-testnet.elastos.io/tx/0xa1864545eff47ef7cccb37af067566c6c133fabd47fd31d8b455b68bea9c51a6/internal-transactions

**Comment by guidiaz** [comment]
Triggering first update ElaUsdPriceFeed:
- https://esc-testnet.elastos.io/tx/0x3bd99f2fe3a66420a3f793d2f506fe691db50feadb368af50fa815d6680fec71/internal-transactions

**Comment by guidiaz** [comment]
Set up new stack in AWS.

**Comment by guidiaz** [comment]
Created change request on https://docs.witnet.io.

**Comment by guidiaz** [comment]
https://feeds.witnet.io/es/elastos
