### ISSUE TITLE
Review pending PRs

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#324]
As to eventually merge into branch `0.7.x`. The goal would not be get these PRs merged, but reviewed and commented.

**Comment by Tommytrg** [comment]
Review the following PRs:
- [ ] #321
- [ ] #322
- [ ] #323

**Comment by Tommytrg** [comment]
Alongside the merge of this PRs, we'll need to include an update in the Witnet docs
