### ISSUE TITLE
Merge latest PRs into branch 0.7.x

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#331]
In testnets where WB and WRF have already been deployed:
- [x] Upgrade WSB contracts suite.
- [x] Verify all contracts, where possible.
- [x] Make sure WitnetRandomness is upgraded as non upgradable.
- [x] WitnetPriceRouter must ofc be kept just as-is and operational.

**Comment by guidiaz** [comment]
Upgraded testnets:
- [ ] Elastos Testnet ==> v0.7.5-

**Comment by guidiaz** [comment]
https://github.com/witnet/witnet-solidity-bridge/pull/334

**Comment by guidiaz** [comment]
Former and preserved WRB and WPR addresses that are ofc kept operational on testnets:
- Moonbase Alpha
- Polygon Mumbai

**Comment by guidiaz** [comment]
New WitnetRandomness address will have to be published for all selected testnets above.

**Comment by guidiaz** [comment]
...pending change request on docs...

**Comment by aesedepece** [comment]
> ...pending change request on docs...

I can't see any change request :thinking:

**Comment by guidiaz** [comment]
Please, try again.

**Comment by aesedepece** [comment]
> Please, try again.

Merged!
