### ISSUE TITLE
Deploy on Boba BNB Testnet

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#346]
https://docs.boba.network/for-developers/multichain/network-bnb

**Comment by guidiaz** [comment]
**Boba BNB Testnet**:
- ChainID: 9728
- RPC: https://testnet.bnb.boba.network
- Gateway: https://gateway.boba.network
- Blockexplorer: https://blockexplorer.testnet.bnb.boba.network/
- Gas cap: 50,000,000

**Comment by guidiaz** [comment]
Got 2.0 tBOBA from authenticated twitter faucet at https://gateway.boba.network/wallet

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/347
-

**Comment by guidiaz** [comment]
**WSB v0.7.7**:
  - **Proxies**:
    - Create2Factory: [`0xDe312a6f7fA35320E8DD109c8ea42e82806DC45b`](https://blockexplorer.testnet.bnb.boba.network/address/0xDe312a6f7fA35320E8DD109c8ea42e82806DC45b)
    - WitnetBytecodes: [`0x0000000e3a3d22d7510B36BdC88994dab11eadc8`](https://blockexplorer.testnet.bnb.boba.network/address/0x0000000e3a3d22d7510B36BdC88994dab11eadc8)
    - WitnetPriceFeeds: [`0x9999999d139bdBFbF25923ba39F63bBFc7593400`](https://blockexplorer.testnet.bnb.boba.network/address/0x9999999d139bdBFbF25923ba39F63bBFc7593400)
    - WitnetRandomness: [`0x88888885966F8F77cC6E797aE263C4d091e44A55`](https://blockexplorer.testnet.bnb.boba.network/address/0x88888885966F8F77cC6E797aE263C4d091e44A55)
    - WitnetRequestBoard: [`0x777777772C24e6CD34B464D1d71616C444254537`](https://blockexplorer.testnet.bnb.boba.network/address/0x777777772C24e6CD34B464D1d71616C444254537)
    - WitnetRequestFactory: [`0x1111111FDE7dC956E3d7922Bc779D9E2349Afb63`](https://blockexplorer.testnet.bnb.boba.network/address/0x1111111FDE7dC956E3d7922Bc779D9E2349Afb63)
  
  - **Libs**:
    - WitnetErrorsLib: [`0x1b91eAB33362f10A5F803Fe3f0d181F42caFaac3`](https://blockexplorer.testnet.bnb.boba.network/address/0x1b91eAB33362f10A5F803Fe3f0d181F42caFaac3)
    - WitnetEncodingLib: [`0xf6d52770453166de85B6B6260Cf22196bC460E88`](https://blockexplorer.testnet.bnb.boba.network/address/0xf6d52770453166de85B6B6260Cf22196bC460E88)
    - WitnetPriceFeedsLib: [`0xA8767A6EA3099De344499B35f725A38E3cD15562`](https://blockexplorer.testnet.bnb.boba.network/address/0xA8767A6EA3099De344499B35f725A38E3cD15562)
  
  - **Implementations**:
    - WitnetProxy: [`0xc71A87657b13A370594967A04b4301a3AcEAF007`](https://blockexplorer.testnet.bnb.boba.network/address/0xc71A87657b13A370594967A04b4301a3AcEAF007)
    - WitnetBytecodesDefault: [`0xeDA4f244FEe1D6a3EA0fB2c0Fc6b7D1c49fEF01D`](https://blockexplorer.testnet.bnb.boba.network/address/0xeDA4f244FEe1D6a3EA0fB2c0Fc6b7D1c49fEF01D)
    - WitnetPriceFeedsUpgradable: [`0xA8f0487eaf3640e30F472b815A45a7d4e96f18CB`](https://blockexplorer.testnet.bnb.boba.network/address/0xA8f0487eaf3640e30F472b815A45a7d4e96f18CB)
    - WitnetPriceRouter: [`0x8D20457d968c937b7cb65be6B8cC766613fBcF28`](https://blockexplorer.testnet.bnb.boba.network/address/0x8D20457d968c937b7cb65be6B8cC766613fBcF28)
    - WitnetRandomnessProxiable: [`0xB4f1f8E27799256ec95C5b5A8d2A5722Bd542E69`](https://blockexplorer.testnet.bnb.boba.network/address/0xB4f1f8E27799256ec95C5b5A8d2A5722Bd542E69)
    - WitnetRequestBoardTrustableOvm2: [`0x4874cb1732eE1167A006E0Ab047D940ACF04D771`](https://blockexplorer.testnet.bnb.boba.network/address/0x4874cb1732eE1167A006E0Ab047D940ACF04D771)
    - WitnetRequestFactoryDefault: [`0x6dc0E2AC80550F901cd4d5F5a4C48333A0ca97Ee`](https://blockexplorer.testnet.bnb.boba.network/address/0x6dc0E2AC80550F901cd4d5F5a4C48333A0ca97Ee)
    - WitnetRequestRandomness: [`0x620e20d91C9b0e11ecAE439E7b85138DA2a1003F`](https://blockexplorer.testnet.bnb.boba.network/address/0x620e20d91C9b0e11ecAE439E7b85138DA2a1003F)

**Comment by guidiaz** [comment]
All contracts could get verified but WitnetRandomnessProxiable.

**Comment by guidiaz** [comment]
Created change request to https://docs.witnet.io

**Comment by aesedepece** [comment]
Hey @guidiaz feel free to merge all related PRs and close this issue :rocket:
