### ISSUE TITLE
Upgrade all testnets to v0.7.9

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-solidity-bridge#356]
And reduce WIT reward on all pf updates.

See https://docs.google.com/spreadsheets/d/17HAUQcrFr8oNUUBAvF0irRC8h8hNNie1MUg_u6KCcwM/edit?usp=sharing.

**Comment by guidiaz** [comment]
Detected and fixed bugs in WitnetBuffer and WitnetEncodingLib:
- https://github.com/witnet/witnet-solidity-bridge/issues/357
- https://github.com/witnet/witnet-solidity-bridge/issues/358

**Comment by guidiaz** [comment]
DoD per testnet:
- WitnetBytecodes, WitnetRequestBoard, WitnetRequestFactory and WitnetPriceFeeds upgraded to 0.7.9
- Pfs routed from WitnetPriceRouter have been replicated into WitnetPriceFeeds
- Pfs routed from WitnetPriceRouter have been upgraded to WitnetPriceFeedBypass
- DFE points to WitnetPriceRouter address
- Poller is upgraded to v2.0.2 in AWS

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/360
- https://github.com/witnet/witnet-feeds/pull/10
- https://github.com/witnet/witnet-price-feeds/pull/264
- https://github.com/otherplane/bridge-iac/pull/105

**Comment by guidiaz** [comment]
As for minimizing Web3 calls, these parameters can be re-set:
- On gateways:
  - `EVM_CALL_INTERLEAVE_BLOCKS = 0` (only in testnets!!)
- On pollers:
  - `WPFP_WEB3_PROVIDER_POLLING_LATENCY_SECS = 10`

**Comment by guidiaz** [comment]
Apparently, Scroll zkEVM supports SHA-256 no more:
- New customized `WitnetBytecodesNoSha256` was deployed into:
  - [ ] Polygon zkEVM Goerli
  - [ ] Scroll zkEVM Goerli

**Comment by guidiaz** [comment]
Missing fallbacks for methods in `IWitnetRequestBoardDeprecating` is provoking older versions of WitnetRandomness to fail. Added fallback in `WitnetRequestBoardTrustableDefault`, to be upgraded in the following testnets:
- [ ] Ethereum Goerli
- [ ] Arbitrum Goerli
- [ ] Avalanche Testnet
- [ ] Boba ETH/Goerli
- [ ] Celo Alfajores
- [ ] Conflux Core Testnet
- [ ] Conflux eSpace Testnet
- [ ] Cronos Testnet
- [ ] Dogechain Testnet
- [ ] Kava Testnet
- [ ] KCC Testnet
- [ ] Klaytn Testnet
- [ ] Meter Testnet
- [ ] OKXChain Testnet
- [ ] Optimism Goerli
- [x] Ultron Testnet

**Comment by guidiaz** [comment]
- https://github.com/witnet/witnet-solidity-bridge/pull/363

**Comment by Tommytrg** [comment]
All testnets are upgraded now
