### ISSUE TITLE
Upgrade Ethereum Mainnet

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-solidity-bridge#434]
- Upgrade Ethereum Mainnet to v2
- Deploy the randomness in Ethereum Mainnet

**Comment by guidiaz** [comment]
WSB v2.0.15 deployed and verified into etherscan.io.

**Comment by guidiaz** [comment]
Settled proper SLA params in legacy WitnetRandomness@0x894907c7Ab64C1092620B5c8Ba039BB6E611eba8 (v0.6).

**Comment by guidiaz** [comment]
Legacy WRB v0.7 bypassed to WitnetOracle v2.0, and verified into etherscan.io.

**Comment by guidiaz** [comment]
Recovered ethereum:mainnet stack into AWS and DFE.

**Comment by guidiaz** [comment]
Smoke tests:
- Randomize on WRv2: https://etherscan.io/tx/0xe44fd5220caddcdea2ea0b94879b558aef7c77f10d555a8925f299254d62ffe1
- Randomize on legacy WR: https://etherscan.io/tx/0x2e535b9e3f2ac8094aa02248af95a91693e010c8f2592c5b19091e867b36e97b

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-solidity-bridge/pull/435
- https://github.com/witnet/witnet-solidity-bridge/pull/436
- https://github.com/witnet/data-feeds-explorer/pull/424
- https://github.com/otherplane/bridge-iac/pull/201
